"""about author column

Revision ID: 0518764abce2
Revises: 7eee9f271f29
Create Date: 2024-05-10 12:11:14.745477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0518764abce2'
down_revision = '7eee9f271f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
