"""Add votes table

Revision ID: 2d93c3389a2a
Revises: ff16febe45b9
Create Date: 2024-05-15 02:54:49.879220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d93c3389a2a'
down_revision = 'ff16febe45b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('vote_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('upvotes')
        batch_op.drop_column('downvotes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downvotes', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upvotes', mysql.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('votes')
    # ### end Alembic commands ###
