"""add total_cost

Revision ID: 3f38cddbc090
Revises: 0c9126d2d093
Create Date: 2024-05-14 00:10:30.430494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f38cddbc090'
down_revision = '0c9126d2d093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_calculation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_calculation', schema=None) as batch_op:
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
